name: Deploy to Cloud Run

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: aztek-native-cloud-run-demo
  SERVICE_NAME: hello-world-service
  REGION: europe-west2
  GAR_REPO: cloud-run-repo
  IMAGE_NAME: hello-world

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Google Auth
        id: auth
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up gcloud
        uses: 'google-github-actions/setup-gcloud@v2'
        with:
          project_id: ${{ env.PROJECT_ID }}

      - name: Build and Push Docker Image
        run: |
          gcloud auth configure-docker ${{
            env.REGION
          }}-docker.pkg.dev
          gcloud builds submit \
            --tag ${{
              env.REGION
            }}-docker.pkg.dev/${{
              env.PROJECT_ID
            }}/${{
              env.GAR_REPO
            }}/${{
              env.IMAGE_NAME
            }} \
            --no-logs-fetch \
            --project=${{
              env.PROJECT_ID
            }}

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy ${{
            env.SERVICE_NAME
          }} \
            --image ${{
              env.REGION
            }}-docker.pkg.dev/${{
              env.PROJECT_ID
            }}/${{
              env.GAR_REPO
            }}/${{
              env.IMAGE_NAME
            }} \
            --platform managed \
            --region ${{
              env.REGION
            }} \
            --allow-unauthenticated \
            --project=${{
              env.PROJECT_ID
            }} 